services:

  rabbitmq:

    restart: unless-stopped

    image: rabbitmq:3.13-management

    container_name: rabbitmq

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    healthcheck:

      test: ["CMD","rabbitmq-diagnostics","check_running"]

      interval: 20s

      timeout: 10s

      retries: 5

    networks:
      - rabbit-network

  springboot:

    restart: unless-stopped

    build: .

    container_name: springboot

    depends_on:

      rabbitmq:
        condition: service_healthy

      prometheus:

        condition: service_started

    environment:

      SPRING_PROFILES_ACTIVE: docker

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

    ports:
      - "8080:8080"

    healthcheck:

      test: ["CMD","wget","--spider","http://localhost:8080/actuator/health"]

      interval: 30s

      timeout: 10s

      retries: 5

    networks:
      - rabbit-network

  prometheus:

    restart: unless-stopped

    image: prom/prometheus

    container_name: prometheus

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

    ports:
      - "9090:9090"

    networks:
      - rabbit-network

  grafana:

    restart: unless-stopped

    image: grafana/grafana

    container_name: grafana

    volumes:
      - grafana-storage:/var/lib/grafana

    ports:
      - "3001:3000"

    networks:
      - rabbit-network

volumes:

  rabbitmq-data:

  grafana-storage:

  prometheus-data:


networks:

   rabbit-network: